# Generated by Django 5.2.7 on 2026-02-07 16:35

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('firstName', models.CharField(max_length=100, verbose_name='Имя')),
                ('middleName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('birthDate', models.DateField(verbose_name='Дата рождения')),
                ('createdAt', models.DateTimeField(verbose_name='Дата создания')),
                ('username', models.CharField(max_length=150, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
                'abstract': False,
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=50, verbose_name='Дом')),
                ('flat', models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира')),
                ('index', models.CharField(max_length=6, verbose_name='Индекс')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('auditLogId', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('tableName', models.CharField(max_length=100, verbose_name='Имя таблицы')),
                ('recordId', models.BigIntegerField(verbose_name='ID записи')),
                ('oldValues', models.JSONField(blank=True, null=True, verbose_name='Старые значения')),
                ('newValues', models.JSONField(blank=True, null=True, verbose_name='Новые значения')),
                ('createdAt', models.DateTimeField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Журнал аудита',
                'verbose_name_plural': 'Журналы аудита',
                'db_table': 'auditLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brandId', models.AutoField(primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=100, verbose_name='Название бренда')),
                ('brandDescription', models.TextField(verbose_name='Описание бренда')),
                ('brandCountry', models.CharField(max_length=100, verbose_name='Страна бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'db_table': 'brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100, verbose_name='Название категории')),
                ('categoryDescription', models.TextField(verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого')),
                ('deliveryType', models.CharField(choices=[('самовывоз', 'Самовывоз'), ('пункт выдачи', 'Пункт выдачи'), ('курьером', 'Курьером')], max_length=20, verbose_name='Тип доставки')),
                ('paymentType', models.CharField(choices=[('онлайн', 'Онлайн'), ('картой при получении', 'Картой при получении'), ('наличными при получении', 'Наличными при получении')], max_length=30, verbose_name='Тип оплаты')),
                ('paymentStatus', models.CharField(choices=[('ждет оплаты', 'Ждет оплаты'), ('оплачено', 'Оплачено'), ('возврат средств', 'Возврат средств'), ('средства возвращены', 'Средства возвращены')], max_length=30, verbose_name='Статус оплаты')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание')),
                ('createdAt', models.DateTimeField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderItemId', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
                'db_table': 'orderItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('orderStatusId', models.AutoField(primary_key=True, serialize=False)),
                ('orderStatusName', models.CharField(max_length=100, verbose_name='Название статуса заказа')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
                'db_table': 'orderStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('parentChildId', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Родитель-ребенок',
                'verbose_name_plural': 'Родитель-ребенок связи',
                'db_table': 'parentChild',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.BigAutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('productDescription', models.TextField(verbose_name='Описание продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('ageRating', models.IntegerField(verbose_name='Возрастной рейтинг')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('weightKg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)')),
                ('dimensions', models.CharField(max_length=50, verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('productAttributeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('productAttributeName', models.CharField(max_length=100, verbose_name='Название атрибута')),
                ('productAttributeValue', models.CharField(max_length=100, verbose_name='Значение атрибута')),
                ('productAttributeUnit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Атрибут продукта',
                'verbose_name_plural': 'Атрибуты продуктов',
                'db_table': 'productAttribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('productImageId', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500, verbose_name='URL изображения')),
                ('altText', models.CharField(max_length=100, verbose_name='Альтернативный текст')),
                ('isMain', models.BooleanField(default=False, verbose_name='Основное изображение')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
                'db_table': 'productImage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('reviewText', models.TextField(blank=True, null=True, verbose_name='Текст отзыва')),
                ('createdAt', models.DateTimeField(verbose_name='Дата создания')),
                ('updatedAt', models.DateTimeField(verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=100, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlistId', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Список желаний',
                'verbose_name_plural': 'Списки желаний',
                'db_table': 'wishlist',
                'managed': False,
            },
        ),
    ]
