from django.urls import path, include
from . import views  # Добавьте этот импорт

urlpatterns = [
    path('', views.info_view, name='info_view'),
    path('catalog/', views.catalog_page, name='catalog'),
    path('product/<int:pk>/', views.product_detail_page, name='product_detail_page'),
    path('login/', views.login_page, name='login_page'),
    path('register/', views.register_page, name='register_page'),
    path('profile/', views.profile_page, name='profile_page'),
    path('wishlist/', views.wishlist_page, name='wishlist_page'),
    path('cart/', views.cart_page, name='cart_page'),
    path('checkout/', views.checkout_page, name='checkout_page'),
    path('payment/', views.payment_page, name='payment_page'),
    path('orders/', views.orders_page, name='orders_page'),
    path('privacy/', views.privacy_page, name='privacy_page'),
    path('admin-panel/', views.admin_panel_page, name='admin_panel_page'),
    
    path('api/catalog/categories/', views.CategoryListView.as_view(), name='categories'),
    path('api/catalog/brands/', views.BrandListView.as_view(), name='brands'),
    path('api/catalog/products/', views.ProductListView.as_view(), name='products'),
    path('api/catalog/products/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('api/catalog/popular-products/', views.PopularProductsListView.as_view(), name='popular-products'),
    path('api/catalog/products/<int:product_id>/reviews/', views.ProductReviewsListView.as_view(), name='product-reviews'),
    
    path('api/auth/register/', views.UserRegistrationView.as_view(), name='user-register'),
    path('api/auth/login/', views.LoginView.as_view(), name='user-login'),
    path('api/auth/profile/', views.UserProfileView.as_view(), name='user-profile'),
    path('api/auth/wishlist/', views.WishlistListView.as_view(), name='user-wishlist'),
    path('api/auth/wishlist/add/', views.WishlistCreateView.as_view(), name='user-wishlist-add'),
    path('api/auth/wishlist/<int:pk>/', views.WishlistDestroyView.as_view(), name='user-wishlist-delete'),
    path('api/auth/cart/', views.CartListView.as_view(), name='user-cart-list'),
    path('api/auth/cart/<int:pk>/', views.CartItemDetailView.as_view(), name='user-cart-item-detail'),
    path('api/auth/addresses/', views.UserAddressListView.as_view(), name='user-addresses-list'),
    path('api/auth/addresses/create/', views.UserAddressCreateView.as_view(), name='user-address-create'),
    path('api/auth/addresses/<int:pk>/', views.UserAddressDeleteView.as_view(), name='user-address-delete'),
    path('api/auth/checkout/delivery-options/', views.CheckoutDeliveryOptionsView.as_view(), name='checkout-delivery-options'),
    path('api/auth/checkout/payment-options/', views.CheckoutPaymentOptionsView.as_view(), name='checkout-payment-options'),
    path('api/auth/checkout/sdek-points/', views.CheckoutSdekPointsView.as_view(), name='checkout-sdek-points'),
    path('api/auth/checkout/create/', views.CreateOrderView.as_view(), name='checkout-create-order'),
    path('api/auth/orders/', views.UserOrdersListView.as_view(), name='user-orders-list'),
    path('api/auth/orders/<int:pk>/', views.UserOrderDetailView.as_view(), name='user-order-detail'),
    path('api/auth/orders/<int:pk>/cancel/', views.UserOrderCancelView.as_view(), name='user-order-cancel'),
    path('api/auth/reviews/', views.UserReviewListCreateView.as_view(), name='user-reviews-list-create'),
    path('api/auth/reviews/<int:pk>/', views.UserReviewDetailView.as_view(), name='user-review-detail'),
    path('api/auth/payment/process/', views.PaymentProcessView.as_view(), name='payment-process'),
    path('api/auth/children/', views.ParentChildrenListView.as_view(), name='user-children-list'),
    path('api/auth/children/<int:pk>/', views.ParentChildDetailView.as_view(), name='user-child-detail'),
    path('api/admin/panel/', views.AdminPanelView.as_view(), name='admin-panel'),
    path('api/admin/dashboard/', views.AdminDashboardView.as_view(), name='admin-dashboard'),
    path('api/admin/products/', views.AdminProductsView.as_view(), name='admin-products'),
    path('api/admin/products/create/', views.AdminProductCreateView.as_view(), name='admin-product-create'),
    path('api/admin/products/<int:pk>/', views.AdminProductDetailView.as_view(), name='admin-product-detail'),
    path('api/admin/products/<int:product_pk>/images/', views.ProductImageViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='product-images-list'),
    path('api/admin/products/<int:product_pk>/images/<int:pk>/', views.ProductImageViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='product-image-detail'),
    path('api/admin/products/<int:product_pk>/attributes/', views.ProductAttributeViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='product-attributes-list'),
    path('api/admin/products/<int:product_pk>/attributes/<int:pk>/', views.ProductAttributeViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='product-attribute-detail'),
    path('api/admin/upload-image/', views.ProductImageUploadView.as_view(), name='admin-upload-image'),
    path('api/admin/categories/', views.AdminCategoryListCreateView.as_view(), name='admin-categories'),
    path('api/admin/categories/<int:pk>/', views.AdminCategoryDetailView.as_view(), name='admin-category-detail'),
    path('api/admin/brands/', views.AdminBrandListCreateView.as_view(), name='admin-brands'),
    path('api/admin/brands/<int:pk>/', views.AdminBrandDetailView.as_view(), name='admin-brand-detail'),
    path('api/admin/users/', views.AdminUsersView.as_view(), name='admin-users'),
    path('api/admin/users/create/', views.AdminUserCreateView.as_view(), name='admin-user-create'),
    path('api/admin/users/<int:pk>/', views.AdminUserDetailView.as_view(), name='admin-user-detail'),
    path('api/admin/roles/', views.RoleListView.as_view(), name='admin-roles'),
    path('api/admin/orders/', views.AdminOrdersView.as_view(), name='admin-orders'),
    path('api/admin/orders/<int:pk>/', views.AdminOrderDetailView.as_view(), name='admin-order-detail'),
    path('api/admin/orders/<int:pk>/mark-paid/', views.AdminOrderMarkPaidView.as_view(), name='admin-order-mark-paid'),
    path('api/admin/order-statuses/', views.AdminOrderStatusListView.as_view(), name='admin-order-statuses'),
    path('api/admin/audit-logs/', views.AdminAuditLogListView.as_view(), name='admin-audit-logs'),
    path('api/admin/reviews/', views.AdminReviewListView.as_view(), name='admin-reviews'),
    path('api/admin/reviews/<int:pk>/', views.AdminReviewDetailView.as_view(), name='admin-review-detail'),
    # Аналитика
    path('api/admin/analytics/sales/', views.AdminAnalyticsSalesView.as_view(), name='admin-analytics-sales'),
    path('api/admin/analytics/products/', views.AdminAnalyticsProductsView.as_view(), name='admin-analytics-products'),
    path('api/admin/analytics/user-activity/', views.AdminUserActivityView.as_view(), name='admin-user-activity'),
    # Хранимые процедуры
    path('api/admin/price-adjustment/', views.AdminPriceAdjustmentView.as_view(), name='admin-price-adjustment'),
]